---
- hosts: webserver
  remote_user: alfredo
  become: yes
  become_method: sudo
  tasks:
    - name: Install pip
      dnf: name=python-pip state=present
  
    - name: install docker-py
      pip: name=docker-py
  
    - name: Build Docker image from Dockerfile
      docker_image:
        name: web
        build:
          path: docker
        state: present
    
    - name: Running the container
      docker_container:
        image: web:latest
        path: docker
        state: running
        
    - name: Check if container is running
      shell: docker ps
